### ISSUE TITLE
Spider: PA Public Utility Commission

### ISSUE THREAD

**Issue by bonfirefan** [bonfirefan/city-scrapers-pitt#25] opened 2019-02-06 20:21 UTC
## Spider Name: 
pa_utility

## Website: 
http://www.puc.state.pa.us/about_puc/public_meeting_calendar.aspx

## Scraping Notes:
Jquery calendar

**Comment by skyejinx** [comment] 2019-02-23 00:25
i'll work on this one

**Comment by bonfirefan** [comment] 2019-04-13 15:31
@skyejinx Just checking in, are you still working on this?

**Comment by categulario** [comment] 2019-04-15 01:55
Because I took it this past friday :paintbrush:

**Comment by bonfirefan** [comment] 2019-04-15 01:56
Ok, thanks @categulario. Make sure to update from upstream, we made some changes!

**Comment by richiebful** [comment] 2019-11-01 23:34
I'm stealing

**Comment by categulario** [comment] 2019-11-02 00:21
Feel free to do it. There's some code in my branch that might be useful. It
was almost ready I think

**Comment by ben-nathanson** [comment] 2020-01-27 03:32
Duplicate of #78

**Closed by ben-nathanson** 2020-01-27 03:32 UTC
Labels: New Spider, pdf
